todoapp/todoapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('todo/', include('todolist.urls')),
    path('admin/', admin.site.urls),
]

todoapp/todolist/urls.py
from django.urls import path

from . import views

app_name = 'todolist'

urlpatterns = [
    # ex: /polls/
    path('', views.OverviewView.as_view(), name='overview'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:todolist_id>/complete/', views.todo_complete, name='complete'),
    path('<int:pk>/notice', views.NoticeView.as_view(), name='notice'),
    path('clear_all/', views.clear_all, name='clear_all'),
]

todoapp/todolist/models.py
import datetime

from django.db import models
from django.utils import timezone


class TodoList(models.Model):
    title = models.CharField(max_length=50)
    completed = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title


class TodoItem(models.Model):
    todolist = models.ForeignKey(TodoList, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    date_created = models.DateTimeField('date created')
    due_date = models.DateTimeField('due date')
    is_completed = models.BooleanField(default=False)

    def days_remaining(self):
        now = timezone.now()
        return (now - self.due_date).days

    def __str__(self):
        return self.name

todoapp/todolist/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.template import loader
from django.views import generic
from django.urls import reverse
from django.utils import timezone

from .models import TodoList, TodoItem


class OverviewView(generic.ListView):
    template_name = 'todolist/overview.html'
    context_object_name = 'all_todo_list'

    def get_queryset(self):
        return TodoList.objects.order_by('title')


class DetailView(generic.DetailView):
    model = TodoList
    template_name = 'todolist/detail.html'


class NoticeView(generic.DetailView):
    model = TodoList
    template_name = 'todolist/notice.html'

    def get_context_data(self, **kwargs):
        print(kwargs)
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        print(context)
        return context


def todo_complete(request, todolist_id):
    todo_list = get_object_or_404(TodoList, pk=todolist_id)
    task_count = len(todo_list.todoitem_set.filter(is_completed=False))
    completed_list = (request.POST.getlist('todo'))
    x = 0
    for i in completed_list:
        # Update item is_completed attribute
        try:
            selected_item = todo_list.todoitem_set.get(pk=int(i))

        except (KeyError, TodoItem.DoesNotExist):
            # Redisplay the question voting form.
            return render(request, 'todolist/detail.html', {
                'todo_list': todo_list,
                'error_message': "You didn't select an item.",
            })
        else:

            if selected_item.is_completed == False:
                x += 1

            selected_item.is_completed = True
            selected_item.save()

        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
    # Update # of completed items inside the db at TodoLists completed attribute
    todo_list.completed += x
    todo_list.save()
    if len(completed_list) == task_count:
        message = "Congratulations, you completed all items in the list!"
    else:
        message = f"You completed {len(completed_list)} out of {task_count} items in the list."
    reversed_url = reverse('todolist:notice', args=(todolist_id,))
    return redirect(reversed_url, {'message': message})
    # return HttpResponseRedirect(reverse('todolist:notice', args=(todolist_id,)), {'message': message})


def clear_all(request):
    # todo_list = get_object_or_404(TodoList, pk=todolist_id)
    my_items = TodoItem.objects.all()

    for i in my_items:
        i.is_completed = False
        i.save()

    my_lists = TodoList.objects.all()

    for l in my_lists:
        l.completed = 0
        l.save()
    print("All items have been cleared")
    return HttpResponseRedirect(reverse('todolist:overview'))

todoapp/todolist/templates/todolist/detail.html
<h1>{{ todolist.title }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'todolist:complete' todolist.id %}" method="post">
{% csrf_token %}
{% for todoitem in todolist.todoitem_set.all %}
{% if todoitem.is_completed == False %}
    <input type="checkbox" name="todo" id="todoitem{{ forloop.counter }}" value="{{ todoitem.id }}">
{% else %}
    <input type="checkbox" name="todo" id="todoitem{{ forloop.counter }}" value="{{ todoitem.id }}" checked>
 {% endif %}
    <label for="todoitem{{ forloop.counter }}">{{ todoitem.name }}</label>:  <i>{{ todoitem.description }}</i><br>

{% endfor %}
<input type="submit" value="Done">
</form>

<a href="{% url 'todolist:overview' %}"><input type="submit" value="Return to List"></a>

todoapp/todolist/templates/todolist/notice.html
<h1>{{ todolist.title }}</h1>
{% if todolist.completed == todolist.todoitem_set.count %}
<p>Congratulation! You completed all items in the list.</p>
{% else %}
<p>You completed {{ todolist.completed }}  out of {{ todolist.todoitem_set.count }} items in the list.</p>
 {% endif %}
<a href="{% url 'todolist:overview' %}"><input type="submit" value="Return to List"></a>

todoapp/todolist/templates/todolist/overview.html
<h1>To-do list Manager</h1>

{% if all_todo_list %}
    <ul>
    {% for item in all_todo_list %}
        <li><a href="{% url 'todolist:detail' item.id %}">{{ item.title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No Todo Lists are available.</p>
{% endif %}
<a href="{% url 'todolist:clear_all' %}"><input type="submit" value="Clear all Lists"></a>